#!/usr/bin/env bash

# Ensure gpg is installed.
if ! command -v gpg >/dev/null 2>&1; then
  echo "Error: gpg is required but was not found." >&2
  exit 1
fi

# Ensure openssl is installed.
if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required but was not found." >&2
  exit 1
fi

# Ensure vim is installed.
if ! command -v vim >/dev/null 2>&1; then
  echo "Error: vim is required but was not found." >&2
  exit 1
fi

PW_PATH="$HOME/.pw"
IDENTITY_FILE_PATH="$PW_PATH/identity"
PW_EXTENSION="pw"

UPPERCASE='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LOWERCASE='abcdefghijklmnopqrstuvwxyz'
NUMBERS='0123456789'
SYMBOLS='!@#$%^&*'
GEN_ALPHABET="$UPPERCASE$LOWERCASE$NUMBERS$SYMBOLS"
GEN_LENGTH=32

CMD=${1-"ls"}

function gen_pw() {
  # biggest multiple of length of alphabet that can fit into 256 to avoid modulo bias
  limit=$((256 / ${#GEN_ALPHABET} * ${#GEN_ALPHABET}))
  # generate 2 x GEN_LENGTH bytes with openssl each invocation
  random_size=$((2 * $GEN_LENGTH))

  generated=""
  while [ "${#generated}" -lt "$GEN_LENGTH" ]; do
    random=$(openssl rand -hex $random_size)

    for ((i = 0; i < ${#random} && ${#generated} < GEN_LENGTH; i += 2 )); do
      byte="${random:i:2}" # get 2 hex characters i.e. 1 byte
      n=$((16#$byte)) # turn hex into an integer
      
      # avoid modulo bias - if we end up with an index >= limit, skip
      [ "$n" -lt "$limit" ] || continue
      
      generated+=${GEN_ALPHABET:n%${#GEN_ALPHABET}:1}
    done
    
  done

  echo "$generated"
}

function decrypt() {
  echo "$(gpg --decrypt --quiet "$1")" | tr -d '\n'
}

function encrypt() {
  gpg --recipient "$1" --output "$3" --encrypt "$2"
}

function total_keys_with_identity() {
  gpg --list-keys --with-colons --quiet | grep "$1" | wc -l | xargs
}

# INITIAL CHECKS

# Ensure that the directory exists (create it if missing)
if [ ! -d "$PW_PATH" ]; then
  mkdir -p "$PW_PATH"
fi

# Load the identity from the file
if [ -e "$IDENTITY_FILE_PATH" ]; then
  IDENTITY=$(cat "$IDENTITY_FILE_PATH" | tr -d '\n')
elif [ "$CMD" == "init" ]; then
  read -p "Enter your email address: " email
    
  matching_keys=$(total_keys_with_identity "$email")
  if [ "$matching_keys" == "0" ]; then
    echo "Generating key..."
    TMP_FILE_PATH=$(mktemp)
    cat > "$TMP_FILE_PATH" <<EOF
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: pw
Name-Email: $email
Expire-Date: 0
%commit
EOF
    gpg --batch --pinentry-mode=ask --full-generate-key --quiet $TMP_FILE_PATH
    rm $TMP_FILE_PATH
  else
    echo "Key already exists. Skipping key generation"
  fi

  echo "Writing identity file $IDENTITY_FILE_PATH"
  echo "$email" > "$IDENTITY_FILE_PATH"
  echo "Initialisation complete"
  exit 0
else
  echo "Not yet initialised. Run 'pw init' to set up"
  exit 1
fi


# ONE ARG COMMANDS

if [ "$CMD" == "init" ]; then
  echo "Already initialized"
  exit 1
fi

if [ "$CMD" == "ls" ]; then
  for f in "$PW_PATH"/*; do
    if [ -f "$f" ]; then
      f="$(basename "$f")"
      ext="${f##*.}"
      if [ "$ext" == "$PW_EXTENSION" ]; then
        echo ${f%.*}
      fi
    fi
  done

  exit 0
fi

if [ "$CMD" == "gen" ]; then
  generated=$(gen_pw)
  echo "$generated"
  exit 0
fi

if [ "$CMD" == "gencp" ]; then
  generated=$(gen_pw)
  echo "$generated" | tr -d '\n' | pbcopy
  echo "Generated and copied to clipboard"
  exit 0
fi

# TWO ARG COMMANDS (name as the second argument)

NAME=$2
if [ -z "$NAME" ]; then
  echo "Usage: $0 $CMD <name>"
  exit 1
fi
PW_FILE_PATH="$PW_PATH/$NAME.$PW_EXTENSION"

if [ "$CMD" == "add" ]; then
  if [ -e "$PW_FILE_PATH" ]; then
    echo "$NAME already exists (path=$PW_FILE_PATH)"
    exit 1
  else
    # https://unit.stackexchange.com/questions/181937/how-to-create-a-temporary-file-in-shall-script
    TMP_FILE_PATH=$(mktemp)
    vim "$TMP_FILE_PATH"
    content=$(<"$TMP_FILE_PATH") # load file contents
    content="${content#"${content%%[![:space:]]*}"}" # trim leading whitespace
    content="${content%"${content##*[![:space:]]}"}" # trim trailing whitespace
    if [[ "$content" == *[[:space:]]* ]]; then
      echo "Whitespace characters (spaces, tabs, newlines etc.) are not allowed in passwords"
      exit 1
    elif [[ "$content" == "" ]]; then
      echo "Password cannot be blank"
      exit 1
    fi
    printf '%s' "$content" > "$TMP_FILE_PATH"
    encrypt "$IDENTITY" "$TMP_FILE_PATH" "$PW_FILE_PATH"
    rm "$TMP_FILE_PATH"
    exit 0
  fi
fi

if [ "$CMD" == "edit" ]; then
  if [ -e "$PW_FILE_PATH" ]; then
    echo "... TODO ..."
    exit 0
  else
    echo "$NAME does not exist (path=$PW_FILE_PATH)"
    exit 1
  fi
fi

if [ "$CMD" == "cp" ]; then
  if [ -e "$PW_FILE_PATH" ]; then
    decrypt $PW_FILE_PATH | pbcopy
    echo "Copied to clipboard"
    exit 0
  else
    echo "$NAME does not exist (path=$PW_FILE_PATH)"
    exit 1
  fi
fi

if [ "$CMD" == "show" ]; then
  if [ -e "$PW_FILE_PATH" ]; then
    VALUE=$(decrypt $PW_FILE_PATH)
    echo "$VALUE"
    exit 0
  else
    echo "$NAME does not exist (path=$PW_FILE_PATH)"
    exit 1
  fi
fi

if [ "$CMD" == "rm" ]; then
  if [ -e "$PW_FILE_PATH" ]; then
    echo "Are you sure you want to delete $NAME? (Warning: this is not reversible)"
    read -p "> Enter DELETE to confirm (anything else will cancel): " confirm
    if [ "$confirm" == "DELETE" ]; then
      rm "$PW_FILE_PATH"
      echo "Deleted $NAME"
      exit 0
    else
      echo "Cancelled deletion of $NAME"
      exit 0
    fi
  else
    echo "$NAME does not exist (path-=$PW_FILE_PATH)"
    exit 1
  fi
fi


echo "Unrecgonised command: $CMD"
exit 1